In [1]:
print("hello numpy")

hello numpy


In [2]:
import numpy as np
lista = np.array([1,2,3,4,5,6,7])
print(lista)

[1 2 3 4 5 6 7]


In [4]:
lista.shape

(7,)

In [6]:
lista[0] = 10
print(lista)

[10  2  3  4  5  6  7]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1,2]

np.int64(7)

In [15]:
a.dtype

dtype('int64')

In [19]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(100,200,2).size

50

In [30]:
np.linspace(1,20,5,dtype=np.int64)

array([ 1,  5, 10, 15, 20])

In [32]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)
print(arr)

[1 2 3 4 5 6 7 8]
